import '../content.dart';


class MockContent {

  static List<Map<String, dynamic> > get all {
    List<Map<String, dynamic> > list = [];

    for (int i=0;i<data.length;i++) {
      list.add(data[i]);
    }

    return list;
  }

  static List<Map<String, dynamic> > data = [
    {
      'title': 'New Item1',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem1',
    },
    {
      'title': 'popular1',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular1',
    },
    {
      'title': 'purcahsed1',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed1',
    },
    {
      'title': 'New Item2',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem2',
    },
    {
      'title': 'popular2',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular2',
    },
    {
      'title': 'purcahsed2',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed2',
    },
    {
      'title': 'New Item3',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem3',
    },
    {
      'title': 'popular3',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular3',
    },
    {
      'title': 'purcahsed3',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed3',
    },
    {
      'title': 'New Item4',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem4',
    },
    {
      'title': 'popular4',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular4',
    },
    {
      'title': 'purcahsed4',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed4',
    },
    {
      'title': 'New Item5',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem5',
    },
    {
      'title': 'popular5',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular5',
    },
    {
      'title': 'purcahsed5',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed5',
    },
    {
      'title': 'New Item6',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem6',
    },
    {
      'title': 'popular6',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular6',
    },
    {
      'title': 'purcahsed6',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed6',
    },
    {
      'title': 'New Item7',
      'caption': 'Buy this new thing',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'newitem7',
    },
    {
      'title': 'popular7',
      'caption': 'Popular stuff',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'popular7',
    },
    {
      'title': 'purcahsed7',
      'caption': 'You already bought this',
      'type': '',
      'keywords': '',
      'size': 100,
      'num_of_likes': 100,
      'num_of_purchases': 100,
      'id': 'purcahsed7',
    },
  ];
}
