import '../content.dart';


class MockContent {

  static List<Map<String, dynamic> > get all {
    List<Map<String, dynamic> > list = [];

    for (int i=0;i<data.length;i++) {
      list.add(data[i]);
    }

    return list;
  }

  static List<Map<String, dynamic> > data = [
    {
      'type': CONTENT.PROFILE,
      'title': 'Jennie',
      'caption': 'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'jennie1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'donghee1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'iu1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': false,
      },
      'cryptlink': 'jackblack1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Snoop Doggy Dog',
      'caption': 'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'snoop1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'tigerwoods1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'details': {
        'sex': 'female',
        'online': false,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'dorothy1',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jennie',
      'caption': 'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'jennie2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'donghee2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'iu2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'jackblack2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Snoop Doggy Dog',
      'caption': 'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'snoop2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'tigerwoods2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'details': {
        'sex': 'female',
        'online': false,
        'verified': false,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'dorothy2',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jennie',
      'caption': 'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'jennie3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'donghee3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'iu3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': true,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'jackblack3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Snoop Doggy Dog',
      'caption': 'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'snoop3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'tigerwoods3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'details': {
        'sex': 'female',
        'online': false,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'dorothy3',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jennie',
      'caption': 'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'jennie4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'donghee4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'iu4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': false,
      },
      'cryptlink': 'jackblack4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Snoop Doggy Dog',
      'caption': 'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'snoop4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'tigerwoods4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'details': {
        'sex': 'female',
        'online': false,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'dorothy4',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jennie',
      'caption': 'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'jennie5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': false,
      },
      'cryptlink': 'donghee5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'details': {
        'sex': 'female',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': true,
      },
      'cryptlink': 'iu5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': true,
        'team_member': true,
        'friend': false,
      },
      'cryptlink': 'jackblack5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Snoop Doggy Dog',
      'caption': 'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'details': {
        'sex': 'male',
        'online': false,
        'verified': true,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'snoop5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'details': {
        'sex': 'male',
        'online': true,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'tigerwoods5',
    },
    {
      'type': CONTENT.PROFILE,
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'details': {
        'sex': 'female',
        'online': false,
        'verified': false,
        'team_member': false,
        'friend': true,
      },
      'cryptlink': 'dorothy5',
    },
  ];
}
