import '../content.dart';


class MockContent {

  static List<Map<String, dynamic> > get all {
    List<Map<String, dynamic> > list = [];

    for (int i=0;i<data.length;i++) {
      list.add(data[i]);
    }

    return list;
  }

  static List<Map<String, dynamic> > data = [
    {
      'title': 'Tables',
      'caption': 'training the model to learn different types of tables',
      'training_data': 'tables1saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'tables1',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups1saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups1',
    },
    {
      'title': 'laptops',
      'caption': 'training the model to learn different types of laptops',
      'training_data': 'laptops1saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'laptops1',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups2saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups2',
    },
    {
      'title': 'Tables',
      'caption': 'training the model to learn different types of tables',
      'training_data': 'tables2saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'tables2',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups2saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups2',
    },
    {
      'title': 'laptops',
      'caption': 'training the model to learn different types of laptops',
      'training_data': 'laptops3saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'laptops3',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups3saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups3',
    },
    {
      'title': 'Tables',
      'caption': 'training the model to learn different types of tables',
      'training_data': 'tables3saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'tables3',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups4saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups4',
    },
    {
      'title': 'laptops',
      'caption': 'training the model to learn different types of laptops',
      'training_data': 'laptops4saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'laptops4',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups4saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups4',
    },
    {
      'title': 'Tables',
      'caption': 'training the model to learn different types of tables',
      'training_data': 'tables5saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'tables5',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups5saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups5',
    },
    {
      'title': 'laptops',
      'caption': 'training the model to learn different types of laptops',
      'training_data': 'laptops5saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'laptops5',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups6saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups6',
    },
      {
      'title': 'Tables',
      'caption': 'training the model to learn different types of tables',
      'training_data': 'tables6saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': true,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'tables6',
    },
    {
      'title': 'cups',
      'caption': 'training the model to learn different types of cups',
      'training_data': 'cups6saghjaehA',
      'encoding_type': 'encryptedStrToImgHash',
      'image_link': '/',
      'author': '47aA0oAG9daQ1Le20fsr',
      'approved': false,
      'created_on': DateTime.parse('20210809'),
      'edited_on': DateTime.now(),
      'uses': 100,
      'id': 'cups6',
    },
  ];
}
